Metrics/LineLength:
  Max: 100
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/Lambda:
  EnforcedStyle: literal
Style/Documentation:
  Enabled: false
Style/AccessModifierIndentation:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: true
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  ExcludedMethods:
    - 'new'
  Exclude:
    - "**/*_spec.rb"
Metrics/MethodLength:
  Max: 20
#   Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
