language: ruby
rvm:
  - 2.3.3
  - 2.4.0
before_install:
  - npm install -g npm@latest
install:
  - bundle install --path vendor/bundle
  - npm install
script:
  - bundle exec rake test
  - bundle exec rake rubocop
